Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  NewCops: disable
